package com.wivlaro.jme3.export;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation for read/write methods of Savable implementations.
 *
 * @author bill
 */
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.METHOD)
public @interface SerializerMethodConfig {
	/** If set to true, the annotated method will be overwritten on next generation. If false (or missing), the method will not be touched. */
	boolean autoGenerated() default false;
}
